apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/crc/weave-gitops
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system