apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: weave-gitops-ui
  namespace: weave-gitops
spec:
  to:
    kind: Service
    name: weave-gitops
  port:
    targetPort: http
  tls:
    termination: edge